// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LearNotes",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "LearNotes",
            targets: ["AppModule"],
            bundleIdentifier: "iago.WWDC2023",
            teamIdentifier: "A7SRF7ZP35",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .smiley),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/diniska/swiftui-wrapping-stack.git", "1.0.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "WrappingStack", package: "swiftui-wrapping-stack")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)